kind: pipeline
name: default

steps:
  - name: publish
    image: rust:1.33-slim
    volumes:
      - name: cargo
        path: /root/.cargo
    commands:
      - cat ~/.cargo/credentials
      - cargo login
      - cargo publish

volumes:
  - name: cargo
    host:
      path: /data/mount/cargo

trigger:
  branch:
    - master
#  event:
#    - tag

